version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs", "vitest"]
  skip_doc_coverage = ["arrow-function-expression"]
  
[[analyzers]]
name = "test-coverage"
enabled = true

