// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​o​n​j​o​u​r​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * A​r​t​i​c​l​e​s
	 */
	blogPosts: string
	/**
	 * e​n
	 */
	languageSwitch: string
	categories: {
		/**
		 * d​e​v​e​l​o​p​m​e​n​t
		 */
		development: string
	}
}

export type TranslationFunctions = {
	/**
	 * Bonjour {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Articles
	 */
	blogPosts: () => LocalizedString
	/**
	 * en
	 */
	languageSwitch: () => LocalizedString
	categories: {
		/**
		 * development
		 */
		development: () => LocalizedString
	}
}

export type Formatters = {}
